name: Link Checker

on:
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest
    name: Validate App and Reference URLs

    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6

    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install requests

    - name: Validate App and Reference URLs
      id: link-check
      env:
        DATA_FILE: _data/collection.json
      run: python .github/workflows/scripts/check_links.py

    - name: Upload Results (Failures and Redirects)
      if: always()
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f  # v7
      with:
        name: validation-results
        path: failed_links.json
